WSL accomodations

diff --git a/vsim b/vsim
--- a/vsim
+++ b/vsim
@@ -69,6 +69,7 @@ vmnet_file="/Library/Preferences/VMware Fusion/networking"
 vmnet1_file="/Library/Preferences/VMware Fusion/vmnet1/dhcpd.conf"
 vmnet8_file="/Library/Preferences/VMware Fusion/vmnet8/dhcpd.conf"
 
+
 # If its not there maybe this is linux
 if ! [ -f "$vmnet_file" ];then vmnet_file="/etc/vmware/networking";fi
 if ! [ -f "$vmnet1_file" ];then vmnet1_file="/etc/vmware/vmnet1/dhcpd/dhcpd.conf";fi
@@ -83,15 +84,30 @@ if [ -f "$vmnet_file" ];then
     vmnet8_subnet=$(cat "$vmnet_file" | grep "VNET_8" | grep "SUBNET" | cut -d' ' -f3)
     vmnet8_netmask=$(cat "$vmnet_file" | grep "VNET_8" | grep "NETMASK" | cut -d' ' -f3)
     vmnet8_gateway=$(cat "$vmnet8_file" | grep -m 1 "routers" | cut -d' ' -f3 | cut -d';' -f1)
-    vmnet8_hostip=$(cat "$vmnet8_file"  | grep "fixed-address" | cut -d' ' -f2 | cut -d';' -f1)
+    #vmnet8_hostip=$(cat "$vmnet8_file"  | grep "fixed-address" | cut -d' ' -f2 | cut -d';' -f1)
     vmnet8_domain=$(cat "$vmnet8_file" | grep -m 1 "domain-name " | cut -d' ' -f3 | cut -d';' -f1)
-    vmnet8_dns=$(cat "$vmnet8_file" | grep -m1 "option domain-name-servers" | cut -d' ' -f3 | cut -d';' -f1)
+    #vmnet8_dns=$(cat "$vmnet8_file" | grep -m1 "option domain-name-servers" | cut -d' ' -f3 | cut -d';' -f1)
     # Populate some read only options
     NAT_SUBNET="$vmnet8_subnet"
     NAT_NETMASK="$vmnet8_netmask"
     NAT_GATEWAY="$vmnet8_gateway"
 fi
 
+# If this is WSL there is a lot more work to do
+if [ -f "/mnt/c/ProgramData/VMware/vmnetdhcp.conf" ];then 
+    vmnet_file="/mnt/c/ProgramData/VMware/vmnetdhcp.conf"
+    #echo "WSL Detected"
+    vmnet1_subnet=$(cat "$vmnet_file" | sed '0,/segment 1/d' | sed '/# End/,$d' | grep "subnet" | cut -d' ' -f2)
+    vmnet1_netmask=$(cat "$vmnet_file" | sed '0,/segment 1/d' | sed '/# End/,$d' | grep "netmask" | cut -d' ' -f4)
+    vmnet1_hostip=$(cat "$vmnet_file"  | sed '0,/segment 1/d' | sed '/# End/,$d' | grep "fixed-address" | tr -s ' ' | cut -d' ' -f 3 | cut -d';' -f 1 )
+    vmnet8_subnet=$(cat "$vmnet_file" | sed '0,/segment 8/d' | sed '/# End/,$d' | grep "subnet" | cut -d' ' -f2)
+    vmnet8_netmask=$(cat "$vmnet_file" | sed '0,/segment 8/d' | sed '/# End/,$d' | grep "netmask" | cut -d' ' -f4)
+    vmnet8_gateway=$(cat "$vmnet_file" | sed '0,/segment 8/d' | sed '/# End/,$d' | grep "routers" | cut -d' ' -f3 | cut -d';' -f 1)
+	vmnet8_domain=$(cat "$vmnet_file" | sed '0,/segment 8/d' | sed '/# End/,$d' | grep -m 1 "domain-name " | cut -d'"' -f2)
+    NAT_SUBNET="$vmnet8_subnet"
+    NAT_NETMASK="$vmnet8_netmask"
+    NAT_GATEWAY="$vmnet8_gateway"
+fi
 ##
 ##  TODO:
 ##
@@ -679,7 +695,8 @@ function cfmount() # $1=vsimpath
 		VMWAREMOUNT=$(which vmware-mount)
 		_partition=$("$VMWAREMOUNT" -p "$_simpath/$_vmdk" | grep "FAT" | cut -d' ' -f2)
 		if [ -z "$_partition" ];then echo "Partition table not supported by vmware-mount";exit;fi
-		_partition=$(fdisk -o device,type -l "$simpath/$_flat"  | grep FAT | sed "s^$simpath/$_flat^^" | cut -d' ' -f1)
+		#_partition=$(fdisk -o device,type -l "$simpath/$_flat"  | grep FAT | sed "s^$simpath/$_flat^^" | cut -d' ' -f1)
+		_partition=$(fdisk -l "$simpath/$_flat"  | grep FAT | sed "s^$simpath/$_flat^^" | cut -d' ' -f1)
 		echo "DISK: $_simpath/$_vmdk"
 		echo "PARTITION: $_partition"
 		"$VMWAREMOUNT" "$_simpath/$_vmdk" "$_partition" "$_simpath/mnt"
@@ -1319,7 +1336,8 @@ function getimagepath() #$1=image
 	OLDIFS=$IFS
 	IFS=";"
 	for i in $ITGZPATH
-	do
+	do  
+	    echo "testing $i/$tgz"
 		if [ -f "$i/$tgz" ];then echo "$i/$tgz";return;fi
 	done
 	IFS=$OLDIFS
@@ -1329,22 +1347,24 @@ function getimagepath() #$1=image
 #find an image.tgz for a given release
 function getreleaseimage() #$1=release
 {
-	prefix=${1//.}
-	if [ -f "$(getimagepath "$prefix""_v_image.tgz")" ]; then
-		echo "$prefix""_v_image.tgz"
-	# ? why would they flip the naming scheme now?
-	elif [ -f "$(getimagepath "image_v_""$prefix"".tgz")" ]; then
-		echo "image_v_""$prefix"".tgz"
-	elif [ -f "$(getimagepath "$prefix""_q_image.tgz")" ]; then
-		echo "$prefix""_q_image.tgz"
-	# and now there are _sim_ and nodar variants
-  elif [ -f "$(getimagepath "$prefix""_q_nodar_image.tgz")" ]; then
-	  echo "$prefix""_q_image_nodar.tgz"
-  elif [ -f "$(getimagepath "$prefix""_sim_image.tgz")" ]; then
-		echo "$prefix""_sim_image.tgz"
-  elif [ -f "$(getimagepath "$prefix""_sim_image_nodar.tgz")" ]; then
-		echo "$prefix""_sim_image_nodar.tgz"
-	fi
+    prefix=${1//.}
+    if [ -f "$(getimagepath "$prefix""_v_image.tgz")" ]; then
+        echo "$prefix""_v_image.tgz"
+    # ? why would they flip the naming scheme now?
+    elif [ -f "$(getimagepath "image_v_""$prefix"".tgz")" ]; then
+        echo "image_v_""$prefix"".tgz"
+    elif [ -f "$(getimagepath "$prefix""_q_image.tgz")" ]; then
+        echo "$prefix""_q_image.tgz"
+    # and now there are _sim_ and nodar variants
+    elif [ -f "$(getimagepath "$prefix""_q_nodar_image.tgz")" ]; then
+        echo "$prefix""_q_image_nodar.tgz"
+    elif [ -f "$(getimagepath "$prefix""_sim_image.tgz")" ]; then
+        echo "$prefix""_sim_image.tgz"
+    elif [ -f "$(getimagepath "$prefix""_sim_image_nodar.tgz")" ]; then
+        echo "$prefix""_sim_image_nodar.tgz"
+    elif [ -f "$(getimagepath "$prefix""_sim_nodar_image.tgz")" ]; then
+        echo "$prefix""_sim_nodar_image.tgz"
+    fi
 }
 
 #find an image.tgz for a given release
@@ -1357,14 +1377,16 @@ function getrelease() #$1=release
 	local _vimagenew=$(getimagepath "image_v_""$_prefix"".tgz")
 	local _simimage=$(getimagepath "$_prefix""_sim_image.tgz")
 	local _simimagenodar=$(getimagepath "$_prefix""_sim_image_nodar.tgz")
-
+	local _simnodarimage=$(getimagepath "$_prefix""_sim_nodar_image.tgz")
+	
 	if [ -f "$_vimage" ];then echo "$_vimage";return 0;fi
 	if [ -f "$_vimagenew" ];then echo "$_vimagenew";return 0;fi
 	if [ -f "$_qimage" ];then echo "$_qimage";return 0;fi
 	if [ -f "$_simimage" ];then echo "$_simimage";return 0;fi
 	if [ -f "$_qimagenodar" ];then echo "$_qimagenodar";return 0;fi
 	if [ -f "$_simimagenodar" ];then echo "$_simimagenodar";return 0;fi
-
+	if [ -f "$_simnodarimage" ];then echo "$_simnodarimage";return 0;fi
+	
 	return 1
 }
 
@@ -1993,7 +2015,8 @@ function newvsimenv() #$1=envfile
 		_part=$(fdisk "$simpath/$_flat" | grep DOS | cut -d: -f1)
 	fi
 	if [ "$(uname)" = "Linux" ];then
-		_part=$(fdisk -o device,type -l "$simpath/$_flat"  | grep FAT | sed "s^$simpath/$_flat^^" | cut -d' ' -f1)
+		#_part=$(fdisk -o device,type -l "$simpath/$_flat"  | grep FAT | sed "s^$simpath/$_flat^^" | cut -d' ' -f1)
+		_part=$(fdisk -l "$simpath/$_flat"  | grep FAT | sed "s^$simpath/$_flat^^" | cut -d' ' -f1)
 	fi
 	if [ -n "$_part" ];then
 		_part=$((0+$_part))
@@ -2013,7 +2036,7 @@ function newvsimenv() #$1=envfile
 	if [ "$_vardev" = "$_cfdevice" ];then _vardev="/dev/ad1s1";fi
 
 	newenv="$1"
-	rm "$1"
+	if [ -f "$1" ];then rm "$1";fi
 	touch "$1"
 	setenv "bootarg.vm" 				"true" 			"$1"
 	setenv "LOADER_VERSION" 			"1.0" 			"$1"
@@ -2717,8 +2740,14 @@ function vsimimport()
 			echo "Vsim: $name"
 			rm -rf "$simpath"
 			mkdir -p "$simpath"
-			vmxfile="$simpath/DataONTAP.vmx"
-			"$OVFTOOL" "--allowAllExtraConfig" "--allowExtraConfig" "--acceptAllEulas" "$filename" "$simpath/DataONTAP.vmx"
+			#WSL Accomodations			
+			_simpath="$simpath"
+			if [ "$(echo $_simpath | grep /mnt/c/)" = "$_simpath" ];then
+			    echo "WSL Detected."
+				_simpath=$(echo $simpath | sed 's^/mnt/c^^g' | sed 's^/^\\^g')
+			fi			
+			vmxfile="$_simpath/DataONTAP.vmx"
+			"$OVFTOOL" "--allowAllExtraConfig" "--allowExtraConfig" "--acceptAllEulas" "$filename" "$vmxfile"
 			if IsVM "$simpath";then
 				_vmdk="$(getcfvmdk)"
 				_flat="$(basename -s .vmdk $_vmdk 2>/dev/null)-flat.vmdk"
@@ -2726,8 +2755,9 @@ function vsimimport()
 				if [ -f "$simpath/$_vmdk" ] && ! [ -f "$simpath/$_flat" ]; then
 					rm "$simpath/tmp.vmdk" 2>/dev/null
 					rm "$simpath/tmp-flat.vmdk" 2>/dev/null
-					"$VDISKMANAGER" -n "$simpath/$_vmdk" "$simpath/tmp.vmdk"
-					"$VDISKMANAGER" -r "$simpath/tmp.vmdk" -t 4 "$simpath/$_vmdk"
+					echo ":: $_simpath/$_vmdk"
+					"$VDISKMANAGER" -n "$_simpath/$_vmdk" "$_simpath/tmp.vmdk"
+					"$VDISKMANAGER" -r "$_simpath/tmp.vmdk" -t 4 "$_simpath/$_vmdk"
 					rm "$simpath/tmp.vmdk" 2>/dev/null
 					rm "$simpath/tmp-flat.vmdk" 2>/dev/null
 				fi
@@ -2948,7 +2978,7 @@ function vsimmake()
   	echo "Name     : $name"
   	echo "location : $simpath"
   	mkdir "$simpath" &> /dev/null
-  	tar -C "$simpath" -xzSf "$_template" --strip=1
+  	tar -C "$simpath" -xzSf "$_template" --strip=1 2>/dev/null
 
 	#Build a clean vmx file
 	echo "VMX File : $vmxfile"
@@ -4198,28 +4228,44 @@ function vsimstart()
 #		fi
 #	fi
 
-
+    _type="Fusion"
+	if [ "$(uname)" = "Linux" ];then _type="ws";fi
+	#WSL Accomodations			
+	_vmxfile="$vmxfile"
+	if [ "$(echo $_vmxfile | grep /mnt/c/)" = "$_vmxfile" ];then
+	    #echo "WSL Detected."
+		_vmxfile=$(echo $_vmxfile | sed 's^/mnt/c^^g' | sed 's^/^\\^g')
+	fi			
   	echo "Starting $name"
- 	"$VMRUN" -T fusion start "$vmxfile" "$_gui" &>/dev/null
+ 	"$VMRUN" -T "$_type" start "$_vmxfile" "$_gui" #&>/dev/null
 }
 
 #Stop a vsim
 function vsimstop()
 {
-	local _hard
+    local _hard
 
-	# And it has to exist
-	if ! [ -d "$simpath" ]; then echo "error:stop: vsim $name not found: $simpath";exit;fi
+    # And it has to exist
+    if ! [ -d "$simpath" ]; then echo "error:stop: vsim $name not found: $simpath";exit;fi
 
-	if $vbox;then echo "vsimstop: vbox graceful shutdown not supported";return 1;fi
+    if $vbox;then echo "vsimstop: vbox graceful shutdown not supported";return 1;fi
 
-	if $force;then _hard="hard";fi
+    if $force;then _hard="hard";fi
 
-	if IsRunning; then
-		echo "Stopping vsim: $name"
-  		"$VMRUN" -T fusion stop "$vmxfile" $_hard &>/dev/null
-			envcache
-  	fi
+    if IsRunning; then
+        echo "Stopping vsim: $name"
+        _type="Fusion"
+        if [ "$(uname)" = "Linux" ];then _type="ws";fi
+        #WSL Accomodations			
+        _vmxfile="$vmxfile"
+        if [ "$(echo $_vmxfile | grep /mnt/c/)" = "$_vmxfile" ];then
+        #echo "WSL Detected."
+        _vmxfile=$(echo $_vmxfile | sed 's^/mnt/c^^g' | sed 's^/^\\^g')
+        fi
+        echo "Starting $name"
+        "$VMRUN" -T "$_type" stop "$_vmxfile" $_hard &>/dev/null
+        envcache
+    fi
 }
 
 #Test code
@@ -4271,7 +4317,8 @@ function cfcache()
 		local _flat="$(basename -s .vmdk $_vmdk 2>/dev/null)-flat.vmdk"
 		local _start="66528"
 		if [ "$(uname)" = "Linux" ];then
-		  local _start="$(fdisk -o start,type -l $simpath/$_flat | grep FAT | cut -d' ' -f 1)";fi
+		  #local _start="$(fdisk -o start,type -l $simpath/$_flat | grep FAT | cut -d' ' -f 1)";fi
+		  local _start="$(fdisk -l $simpath/$_flat | grep FAT | tr -s ' ' | cut -d' ' -f 2)";fi
 		if [ "$(uname)" = "Darwin" ];then
 		  local _start="$(fdisk -d $simpath/$_flat | grep 0x06 | cut -d, -f1)";fi
 		local _offset="$(echo $_start / 2 |bc)k"
@@ -4298,7 +4345,8 @@ function cfsave()
 		local _flat="$(basename -s .vmdk $_vmdk 2>/dev/null)-flat.vmdk"
 		local _start="66528"
 		if [ "$(uname)" = "Linux" ];then
-		  local _start="$(fdisk -o start,type -l $simpath/$_flat | grep FAT | cut -d' ' -f 1)";fi
+		  #local _start="$(fdisk -o start,type -l $simpath/$_flat | grep FAT | cut -d' ' -f 1)";fi
+          local _start="$(fdisk -l $simpath/$_flat | grep FAT | tr -s ' ' | cut -d' ' -f 2)";fi
 		if [ "$(uname)" = "Darwin" ];then
 		  local _start="$(fdisk -d $simpath/$_flat | grep 0x06 | cut -d, -f1)";fi
 		local _offset="$(echo $_start / 2 |bc)k"
@@ -4355,7 +4403,8 @@ function envcache()
 		local _flat="$(basename -s .vmdk $_vmdk 2>/dev/null)-flat.vmdk"
 		local _start="66528"
 		if [ "$(uname)" = "Linux" ];then
-		  local _start="$(fdisk -o start,type -l $simpath/$_flat | grep FAT | cut -d' ' -f 1)";fi
+		  #local _start="$(fdisk -o start,type -l $simpath/$_flat | grep FAT | cut -d' ' -f 1)";fi
+          local _start="$(fdisk -l $simpath/$_flat | grep FAT | tr -s ' ' | cut -d' ' -f 2)";fi
 		if [ "$(uname)" = "Darwin" ];then
 		  local _start="$(fdisk -d $simpath/$_flat | grep 0x06 | cut -d, -f1)";fi
 		local _offset="$(echo $_start / 2 |bc)k"
@@ -4402,7 +4451,8 @@ function envsave()
 		local _flat="$(basename -s .vmdk $_vmdk 2>/dev/null)-flat.vmdk"
 		local _start="66528"
 		if [ "$(uname)" = "Linux" ];then
-		  local _start="$(fdisk -o start,type -l $simpath/$_flat | grep FAT | cut -d' ' -f 1)";fi
+		  #local _start="$(fdisk -o start,type -l $simpath/$_flat | grep FAT | cut -d' ' -f 1)";fi
+          local _start="$(fdisk -l $simpath/$_flat | grep FAT | tr -s ' ' | cut -d' ' -f 2)";fi
 		if [ "$(uname)" = "Darwin" ];then
 		  local _start="$(fdisk -d $simpath/$_flat | grep 0x06 | cut -d, -f1)";fi
 		local _offset="$(echo $_start / 2 |bc)k"
@@ -4813,7 +4863,7 @@ fi
 
 #For these commands, exit if the VM is still running
 case $action in
-	export|clean|create|modify|setenv|setvmx|start|unsetenv|unsetvmx|update|makecons )
+	export|clean|create|modify|setenv|setvmx|unsetenv|unsetvmx|update|makecons )
 		if IsRunning; then echo "error: vsim is still running: $simpath";exit;fi;;
 esac
 
@@ -4836,7 +4886,8 @@ case $action in
 			_flat="$(basename -s .vmdk $_vmdk 2>/dev/null)-flat.vmdk"
 			_start="66528"
 			if [ "$(uname)" = "Linux" ];then
-			  _start="$(fdisk -o start,type -l $simpath/$_flat | grep FAT | cut -d' ' -f 1)";fi
+			  #_start="$(fdisk -o start,type -l $simpath/$_flat | grep FAT | cut -d' ' -f 1)";fi
+              _start="$(fdisk -l $simpath/$_flat | grep FAT | tr -s ' ' | cut -d' ' -f 2)";fi
 			if [ "$(uname)" = "Darwin" ];then
 			  _start="$(fdisk -d $simpath/$_flat | grep 0x06 | cut -d, -f1)";fi
 			_offset="$(echo $_start / 2 |bc)k"
@@ -4869,8 +4920,18 @@ case $action in
 
 		#If its a VM then stop & delete it
 		if [ -f "$vmxfile" ];then
-			"$VMRUN" -T fusion stop "$vmxfile" hard &>/dev/null
-			"$VMRUN" -T fusion deleteVM "$vmxfile"
+			force=true
+			vsimstop
+            _type="Fusion"
+            if [ "$(uname)" = "Linux" ];then _type="ws";fi
+            #WSL Accomodations			
+            _vmxfile="$vmxfile"
+            if [ "$(echo $_vmxfile | grep /mnt/c/)" = "$_vmxfile" ];then
+            #echo "WSL Detected."
+            _vmxfile=$(echo $_vmxfile | sed 's^/mnt/c^^g' | sed 's^/^\\^g')
+            fi			
+
+			"$VMRUN" -T "$_type" deleteVM "$_vmxfile"
   			rm -rf "$simpath"
   		fi
 
